///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SkyTestSuite
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Test1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.2")]
    [RepositoryFolder("09ad0020-c27d-478a-a523-fec26dcd45f2")]
    public partial class Test1Repository : RepoGenBaseFolder
    {
        static Test1Repository instance = new Test1Repository();
        Test1RepositoryFolders.ComSkyPremiumLtdSkyPremiumAppFolder _comskypremiumltdskypremium;

        /// <summary>
        /// Gets the singleton class instance representing the Test1Repository element repository.
        /// </summary>
        [RepositoryFolder("09ad0020-c27d-478a-a523-fec26dcd45f2")]
        public static Test1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Test1Repository() 
            : base("Test1Repository", "/", null, 0, false, "09ad0020-c27d-478a-a523-fec26dcd45f2", ".\\RepositoryImages\\SkyTestSuiteRepository09ad0020.rximgres")
        {
            _comskypremiumltdskypremium = new Test1RepositoryFolders.ComSkyPremiumLtdSkyPremiumAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("09ad0020-c27d-478a-a523-fec26dcd45f2")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ComSkyPremiumLtdSkyPremium folder.
        /// </summary>
        [RepositoryFolder("189902cb-117e-4654-b17d-12cb1665a0c1")]
        public virtual Test1RepositoryFolders.ComSkyPremiumLtdSkyPremiumAppFolder ComSkyPremiumLtdSkyPremium
        {
            get { return _comskypremiumltdskypremium; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.2")]
    public partial class Test1RepositoryFolders
    {
        /// <summary>
        /// The ComSkyPremiumLtdSkyPremiumAppFolder folder.
        /// </summary>
        [RepositoryFolder("189902cb-117e-4654-b17d-12cb1665a0c1")]
        public partial class ComSkyPremiumLtdSkyPremiumAppFolder : RepoGenBaseFolder
        {
            Test1RepositoryFolders.ContentFolder _content;
            RepoItemInfo _rstringmsgpushconfirmnoInfo;
            RepoItemInfo _skymainactivityInfo;
            RepoItemInfo _linearInfo;

            /// <summary>
            /// Creates a new ComSkyPremiumLtdSkyPremium  folder.
            /// </summary>
            public ComSkyPremiumLtdSkyPremiumAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ComSkyPremiumLtdSkyPremium", "/mobileapp[@title='com.SkyPremiumLtd.SkyPremium']", parentFolder, 30000, null, false, "189902cb-117e-4654-b17d-12cb1665a0c1", "")
            {
                _content = new Test1RepositoryFolders.ContentFolder(this);
                _rstringmsgpushconfirmnoInfo = new RepoItemInfo(this, "RStringMsgPushConfirmNo", "form[@title='(none)']/container[@rid='content']//text[@resourceid='R.string.msg_push_confirm_no']", 30000, null, "891f8e83-ff4b-4c72-976d-453c316f8964");
                _skymainactivityInfo = new RepoItemInfo(this, "SkyMainActivity", "form[@title='SkyMainActivity']", 30000, null, "2b345434-d6e3-4bfd-be84-6b71890264c8");
                _linearInfo = new RepoItemInfo(this, "Linear", "form[@title='SkyMainActivity']/container[@rid='content']/?/?/container[@rid='content_frame']//container[@containertype='Linear']/container[@containertype='Relative']/list[@rid='list']/container[1]/?/?/container[@containertype='Relative']/container[@containertype='Linear']", 30000, null, "206b831c-e3d7-4d0f-882b-d3c8ee529a67");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("189902cb-117e-4654-b17d-12cb1665a0c1")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("189902cb-117e-4654-b17d-12cb1665a0c1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RStringMsgPushConfirmNo item.
            /// </summary>
            [RepositoryItem("891f8e83-ff4b-4c72-976d-453c316f8964")]
            public virtual Ranorex.Text RStringMsgPushConfirmNo
            {
                get
                {
                    return _rstringmsgpushconfirmnoInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RStringMsgPushConfirmNo item info.
            /// </summary>
            [RepositoryItemInfo("891f8e83-ff4b-4c72-976d-453c316f8964")]
            public virtual RepoItemInfo RStringMsgPushConfirmNoInfo
            {
                get
                {
                    return _rstringmsgpushconfirmnoInfo;
                }
            }

            /// <summary>
            /// The SkyMainActivity item.
            /// </summary>
            [RepositoryItem("2b345434-d6e3-4bfd-be84-6b71890264c8")]
            public virtual Ranorex.Form SkyMainActivity
            {
                get
                {
                    return _skymainactivityInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The SkyMainActivity item info.
            /// </summary>
            [RepositoryItemInfo("2b345434-d6e3-4bfd-be84-6b71890264c8")]
            public virtual RepoItemInfo SkyMainActivityInfo
            {
                get
                {
                    return _skymainactivityInfo;
                }
            }

            /// <summary>
            /// The Linear item.
            /// </summary>
            [RepositoryItem("206b831c-e3d7-4d0f-882b-d3c8ee529a67")]
            public virtual Ranorex.Container Linear
            {
                get
                {
                    return _linearInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Linear item info.
            /// </summary>
            [RepositoryItemInfo("206b831c-e3d7-4d0f-882b-d3c8ee529a67")]
            public virtual RepoItemInfo LinearInfo
            {
                get
                {
                    return _linearInfo;
                }
            }

            /// <summary>
            /// The Content folder.
            /// </summary>
            [RepositoryFolder("784cba61-6670-4daf-b83f-6c1c852eacce")]
            public virtual Test1RepositoryFolders.ContentFolder Content
            {
                get { return _content; }
            }
        }

        /// <summary>
        /// The ContentFolder folder.
        /// </summary>
        [RepositoryFolder("784cba61-6670-4daf-b83f-6c1c852eacce")]
        public partial class ContentFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rstringmsgsigninInfo;
            RepoItemInfo _loginInfo;
            RepoItemInfo _passwordInfo;

            /// <summary>
            /// Creates a new Content  folder.
            /// </summary>
            public ContentFolder(RepoGenBaseFolder parentFolder) :
                    base("Content", "form[@title='RootActivity']/container[@rid='content']", parentFolder, 30000, null, false, "784cba61-6670-4daf-b83f-6c1c852eacce", "")
            {
                _rstringmsgsigninInfo = new RepoItemInfo(this, "RStringMsgSignIn", ".//container[@rid='loginmain']/text[@resourceid='R.string.msg_sign_in']", 30000, null, "0cab3d7a-1485-4b19-8a34-e1fd7e5da4c9");
                _loginInfo = new RepoItemInfo(this, "Login", "container[@rid='root']/?/?/container[@rid='parent_id']/?/?/container[@rid='loginmain']//text[@rid='login']", 30000, null, "d4c3a82e-07eb-4bc5-a39d-cd7544ca1712");
                _passwordInfo = new RepoItemInfo(this, "Password", "container[@rid='root']/?/?/container[@rid='parent_id']/?/?/container[@rid='loginmain']//text[@rid='password']", 30000, null, "7852e353-6d5d-4f0b-b2cd-32e13c94ea6d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("784cba61-6670-4daf-b83f-6c1c852eacce")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("784cba61-6670-4daf-b83f-6c1c852eacce")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RStringMsgSignIn item.
            /// </summary>
            [RepositoryItem("0cab3d7a-1485-4b19-8a34-e1fd7e5da4c9")]
            public virtual Ranorex.Text RStringMsgSignIn
            {
                get
                {
                    return _rstringmsgsigninInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RStringMsgSignIn item info.
            /// </summary>
            [RepositoryItemInfo("0cab3d7a-1485-4b19-8a34-e1fd7e5da4c9")]
            public virtual RepoItemInfo RStringMsgSignInInfo
            {
                get
                {
                    return _rstringmsgsigninInfo;
                }
            }

            /// <summary>
            /// The Login item.
            /// </summary>
            [RepositoryItem("d4c3a82e-07eb-4bc5-a39d-cd7544ca1712")]
            public virtual Ranorex.Text Login
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Login item info.
            /// </summary>
            [RepositoryItemInfo("d4c3a82e-07eb-4bc5-a39d-cd7544ca1712")]
            public virtual RepoItemInfo LoginInfo
            {
                get
                {
                    return _loginInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("7852e353-6d5d-4f0b-b2cd-32e13c94ea6d")]
            public virtual Ranorex.Text Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("7852e353-6d5d-4f0b-b2cd-32e13c94ea6d")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}