///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SkyTestSuite
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Test003_login recording.
    /// </summary>
    [TestModule("781c5916-2f50-470d-af0a-5b9e8a9072d4", ModuleType.Recording, 1)]
    public partial class Test003_login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Test1Repository repository.
        /// </summary>
        public static Test1Repository repo = Test1Repository.Instance;

        static Test003_login instance = new Test003_login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Test003_login()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Test003_login Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run mobile app 'com.SkyPremiumLtd.SkyPremium' on device '$deviceIDAndrroid'.", new RecordItemIndex(0));
            Host.Local.RunMobileApp("$deviceIDAndrroid", "com.SkyPremiumLtd.SkyPremium", true);
            Delay.Milliseconds(3500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComSkyPremiumLtdSkyPremium.Content.Login' at 66;45", repo.ComSkyPremiumLtdSkyPremium.Content.LoginInfo, new RecordItemIndex(1));
            repo.ComSkyPremiumLtdSkyPremium.Content.Login.Touch("66;45");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '011140417B' on item 'ComSkyPremiumLtdSkyPremium.Content.Login'.", repo.ComSkyPremiumLtdSkyPremium.Content.LoginInfo, new RecordItemIndex(2));
            repo.ComSkyPremiumLtdSkyPremium.Content.Login.Element.SetAttributeValue("Text", "011140417B");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComSkyPremiumLtdSkyPremium.Content.Password' at 65;46", repo.ComSkyPremiumLtdSkyPremium.Content.PasswordInfo, new RecordItemIndex(3));
            repo.ComSkyPremiumLtdSkyPremium.Content.Password.Touch("65;46");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '1234567a' on item 'ComSkyPremiumLtdSkyPremium.Content.Password'.", repo.ComSkyPremiumLtdSkyPremium.Content.PasswordInfo, new RecordItemIndex(4));
            repo.ComSkyPremiumLtdSkyPremium.Content.Password.Element.SetAttributeValue("Text", "1234567a");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComSkyPremiumLtdSkyPremium.Content.RStringMsgSignIn' at 113;48", repo.ComSkyPremiumLtdSkyPremium.Content.RStringMsgSignInInfo, new RecordItemIndex(5));
            repo.ComSkyPremiumLtdSkyPremium.Content.RStringMsgSignIn.Touch("113;48");
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
