///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SkyTestSuite
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Test001_insttall_apk recording.
    /// </summary>
    [TestModule("b7c8d521-df31-43d7-95c8-c42a5ec1a8ee", ModuleType.Recording, 1)]
    public partial class Test001_insttall_apk : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Test1Repository repository.
        /// </summary>
        public static Test1Repository repo = Test1Repository.Instance;

        static Test001_insttall_apk instance = new Test001_insttall_apk();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Test001_insttall_apk()
        {
            deviceIDAndrroid = "USB-0123456789ABCDEF";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Test001_insttall_apk Instance
        {
            get { return instance; }
        }

#region Variables

        string _deviceIDAndrroid;

        /// <summary>
        /// Gets or sets the value of variable deviceIDAndrroid.
        /// </summary>
        [TestVariable("8e35c22c-5bae-4406-b5a1-11878f47a23d")]
        public string deviceIDAndrroid
        {
            get { return _deviceIDAndrroid; }
            set { _deviceIDAndrroid = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Deploying android app 'C:\\Users\\tv\\Desktop\\test\\Sky.apk' to device from variable '$deviceIDAndrroid'.", new RecordItemIndex(0));
            Host.Local.InstrumentAndDeployAndroidApp(deviceIDAndrroid, "C:\\Users\\tv\\Desktop\\test\\Sky.apk", true, Host.DeploymentModes.Auto, 600000, new Ranorex.Core.Remoting.RecordItems.InstrumentApkOptions() { InstrumentationFlags = "", EnableWebTesting = true, TreeSimplification = true, FullImageComparison = true, RIdClass = "", KeyStore = "", KeyAlias = "", JdkBinPath = "", KeyStorePass = "", KeyPass = "" });
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
